backend:
  name: git-gateway
  branch: main
  build_hook: https://api.netlify.com/build_hooks/664a498f92f790f76188a765
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Enter the title of the blog post.",
        }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          hint: "Enter the author's name.",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          hint: "Select the publish date and time.",
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          hint: "Upload a featured image for the post.",
        }
      - {
          label: "Featured Text",
          name: "featuredText",
          widget: "text",
          hint: "Enter a short description or excerpt.",
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          editor: "rich_text",
          hint: "Write the main content of the post here. Use the toolbar to add images, format text, and more.",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          field: { name: "tag", widget: "string" },
          hint: "Add relevant tags to categorize the post.",
        }
